# 1주차 예상문제 1

데이터 출처 : https://www.kaggle.com/shubh0799/churn-modelling 에서 변형

데이터 설명 :  고객의 신상정보 데이터를 통한 회사 서비스 이탈 예측 (종속변수 : Exited)

문제타입 : 분류유형

평가지표 : f1-score

trainData url : https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/train.csv

testData url : https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/test.csv

subData url : https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/submission.csv

출처 : 1주차 예상문제 1 (이기적 스터디 카페 / 컴활,정보처리,빅분기) | 작성자 빅분기 조교

In [1]:
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/test.csv")
submission = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/submission.csv", index_col=0)

In [2]:
submission

Empty DataFrame
Columns: []
Index: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]

[2001 rows x 0 columns]

In [3]:
train

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,6842,15793491,Cherkasova,714,Germany,Male,26,3,119545.48,2,1,0,65482.94,0
1,8963,15607874,Keane,687,France,Male,38,0,144450.58,1,0,1,137276.83,0
2,7047,15737627,Rivero,589,Germany,Female,20,2,121093.29,2,1,0,3529.72,0
3,7503,15697844,Whitehouse,721,Spain,Female,32,10,0.00,1,1,0,136119.96,1
4,3439,15722404,Carpenter,445,France,Female,30,3,0.00,2,1,1,127939.19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,1607,15714080,Goliwe,566,Germany,Female,40,2,97001.36,2,1,0,154486.01,0
7995,7744,15741643,Chiang,777,Germany,Male,35,7,122917.69,1,1,1,76169.68,0
7996,4231,15566660,Cole,670,France,Female,41,10,0.00,3,1,0,81602.02,0
7997,8870,15733597,Y?an,669,France,Female,41,0,150219.41,2,0,0,107839.03,0
7998,523,15595766,Watts,527,Spain,Male,37,5,93722.73,2,1,1,139093.73,0

In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

## 전처리

In [5]:
train = train.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
l1 = LabelEncoder()
l2 = LabelEncoder()

train['Geography'] = l1.fit_transform(train['Geography'])
train['Gender'] = l2.fit_transform(train['Gender'])

In [6]:
test = test.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

test['Geography'] = l1.transform(test['Geography'])
test['Gender'] = l2.transform(test['Gender'])

## 데이터 분리

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = train.drop('Exited', axis=1)
y = train['Exited']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

## 모델 학습

In [10]:
model = RandomForestClassifier(random_state=42, n_estimators=1000)

In [11]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

## 모델 평가

In [12]:
from sklearn.metrics import f1_score

In [13]:
print(f1_score(y_test, y_pred))

0.5684754521963824

## 제출

In [14]:
test_pred = model.predict(test)

In [15]:
submission[0] = test_pred

In [16]:
submission

     0
0
0.0  0
0.0  0
0.0  0
0.0  0
0.0  1
..  ..
0.0  0
0.0  0
0.0  0
0.0  0
0.0  1

[2001 rows x 1 columns]

In [17]:
submission.to_csv('submission_1주차_1.csv', index=False)

# 1주차 예상문제 2

데이터 출처 : https://archive.ics.uci.edu/ml/datasets/Breast%20Cancer%20Wisconsin%20(Diagnostic)에서 변형

데이터 설명 :  유방암 발생여부 예측 (종속변수 diagnosis : B(양성)  , M(악성) )

문제타입 : 분류유형

평가지표 : f1-score

trainData url : https://raw.githubusercontent.com/Datamanim/datarepo/main/cancer/train.csv

testData url : https://raw.githubusercontent.com/Datamanim/datarepo/main/cancer/test.csv

subData url : https://raw.githubusercontent.com/Datamanim/datarepo/main/cancer/submission.csv

출처 : 1주차 예상문제 2 (이기적 스터디 카페 / 컴활,정보처리,빅분기) | 작성자 빅분기 조교

In [18]:
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/cancer/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/cancer/test.csv")
submission = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/cancer/submission.csv")

In [19]:
train

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,points_worst,symmetry_worst,dimension_worst
0,8812844,B,10.18,17.53,65.12,313.1,0.10610,0.08502,0.01768,0.01915,...,11.17,22.84,71.94,375.6,0.14060,0.1440,0.06572,0.05575,0.3055,0.08797
1,904689,B,12.96,18.29,84.18,525.2,0.07351,0.07899,0.04057,0.01883,...,14.13,24.61,96.31,621.9,0.09329,0.2318,0.16040,0.06608,0.3207,0.07247
2,924632,B,12.88,28.92,82.50,514.3,0.08123,0.05824,0.06195,0.02343,...,13.89,35.74,88.84,595.7,0.12270,0.1620,0.24390,0.06493,0.2372,0.07242
3,924084,B,12.77,29.43,81.35,507.9,0.08276,0.04234,0.01997,0.01499,...,13.87,36.00,88.10,594.7,0.12340,0.1064,0.08653,0.06498,0.2407,0.06484
4,9011495,B,12.21,18.02,78.31,458.4,0.09231,0.07175,0.04392,0.02027,...,14.29,24.04,93.85,624.6,0.13680,0.2170,0.24130,0.08829,0.3218,0.07470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,861648,B,14.62,24.02,94.57,662.7,0.08974,0.08606,0.03102,0.02957,...,16.11,29.11,102.90,803.7,0.11150,0.1766,0.09189,0.06946,0.2522,0.07246
450,911150,B,14.53,19.34,94.25,659.7,0.08388,0.07800,0.08817,0.02925,...,16.30,28.39,108.10,830.5,0.10890,0.2649,0.37790,0.09594,0.2471,0.07463
451,855563,M,10.95,21.35,71.90,371.1,0.12270,0.12180,0.10440,0.05669,...,12.84,35.34,87.22,514.0,0.19090,0.2698,0.40230,0.14240,0.2964,0.09606
452,893061,B,11.60,24.49,74.23,417.2,0.07474,0.05688,0.01974,0.01313,...,12.44,31.62,81.39,476.5,0.09545,0.1361,0.07239,0.04815,0.3244,0.06745
453,901041,B,13.30,21.57,85.24,546.1,0.08582,0.06373,0.03344,0.02424,...,14.20,29.20,92.94,621.2,0.11400,0.1667,0.12120,0.05614,0.2637,0.06658

In [20]:
test

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,points_worst,symmetry_worst,dimension_worst
0,915186,9.268,12.87,61.49,248.7,0.16340,0.22390,0.09730,0.05252,0.2378,...,10.28,16.38,69.05,300.2,0.1902,0.34410,0.20990,0.10250,0.3038,0.12520
1,869224,12.900,15.92,83.74,512.2,0.08677,0.09509,0.04894,0.03088,0.1778,...,14.48,21.82,97.17,643.8,0.1312,0.25480,0.20900,0.10120,0.3549,0.08118
2,857374,11.940,18.24,75.71,437.6,0.08261,0.04751,0.01972,0.01349,0.1868,...,13.10,21.33,83.67,527.2,0.1144,0.08906,0.09203,0.06296,0.2785,0.07408
3,866458,15.100,16.39,99.58,674.5,0.11500,0.18070,0.11380,0.08534,0.2001,...,16.11,18.33,105.90,762.6,0.1386,0.28830,0.19600,0.14230,0.2590,0.07779
4,91762702,24.630,21.60,165.50,1841.0,0.10300,0.21060,0.23100,0.14710,0.1991,...,29.92,26.93,205.70,2642.0,0.1342,0.41880,0.46580,0.24750,0.3157,0.09671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,88143502,14.340,13.47,92.51,641.2,0.09906,0.07624,0.05724,0.04603,0.2075,...,16.77,16.90,110.40,873.2,0.1297,0.15250,0.16320,0.10870,0.3062,0.06072
111,9010598,12.760,18.84,81.87,496.6,0.09676,0.07952,0.02688,0.01781,0.1759,...,13.75,25.99,87.82,579.7,0.1298,0.18390,0.12550,0.08312,0.2744,0.07238
112,846226,19.170,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.11180,0.2397,...,20.96,29.94,151.70,1332.0,0.1037,0.39030,0.36390,0.17670,0.3176,0.10230
113,906539,11.570,19.04,74.20,409.7,0.08546,0.07722,0.05485,0.01428,0.2031,...,13.07,26.98,86.43,520.5,0.1249,0.19370,0.25600,0.06664,0.3035,0.08284
114,877486,19.180,22.49,127.50,1148.0,0.08523,0.14280,0.11140,0.06772,0.1767,...,23.36,32.06,166.40,1688.0,0.1322,0.56010,0.38650,0.17080,0.3193,0.09221

## 전처리

In [21]:
train = train.drop(['id'], axis=1)
X = train.drop(['diagnosis'], axis=1)
y = train['diagnosis'].map(lambda x: 1 if x=='B' else 0)

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [23]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

## 데이터 분리

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y)

## 모델 학습

In [26]:
model = RandomForestClassifier(random_state=42)

In [27]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [28]:
y_pred = model.predict(X_test)

## 모델 평가

In [29]:
from sklearn.metrics import f1_score

In [30]:
f1_score(y_test, y_pred)

0.9599999999999999

## 제출

In [31]:
test = test.drop(['id'], axis=1)
test = scaler.transform(test)
test_pred = model.predict(test)

In [32]:
test_pred

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0], dtype=int64)

In [33]:
submission[0] = test_pred
submission.to_csv("submission_1주차_2.csv", index=False)