# 8주차 예상문제 1

데이터 출처 :https://www.kaggle.com/kyr7plus/emg-4(참고, 데이터 수정)

데이터 설명 : 센서데이터로 동작 유형 분류

Data url :https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/train.csv

출처 : 8주차 예상문제 1 (이기적 스터디 카페 / 컴활,정보처리,빅분기) | 작성자 빅분기 실기조교

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/train.csv")

In [2]:
df

,motion_0,motion_1,motion_2,motion_3,motion_4,motion_5,motion_6,motion_7,motion_8,motion_9,...,motion_55,motion_56,motion_57,motion_58,motion_59,motion_60,motion_61,motion_62,motion_63,pose
0,-6.0,8.0,5.0,6.0,-12.0,-27.0,5.0,24.0,-8.0,-5.0,...,-1.0,-3.0,-6.0,-9.0,-7.0,36.0,68.0,3.0,-3.0,1
1,-32.0,-3.0,-4.0,-5.0,-1.0,16.0,0.0,-5.0,42.0,2.0,...,-17.0,-12.0,-1.0,-1.0,0.0,-26.0,-11.0,-4.0,-9.0,1
2,35.0,-2.0,-1.0,1.0,-25.0,-16.0,-3.0,-20.0,10.0,1.0,...,6.0,-65.0,6.0,-10.0,-31.0,-19.0,-3.0,-47.0,-17.0,0
3,-15.0,-6.0,-3.0,-5.0,27.0,37.0,-2.0,-2.0,19.0,5.0,...,2.0,11.0,0.0,-2.0,-4.0,-7.0,15.0,3.0,14.0,1
4,60.0,3.0,0.0,-7.0,-6.0,-10.0,-6.0,7.0,-11.0,-4.0,...,-12.0,17.0,-3.0,1.0,2.0,-2.0,20.0,18.0,10.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4645,40.0,-8.0,-14.0,-27.0,10.0,12.0,-35.0,12.0,-21.0,1.0,...,84.0,-1.0,2.0,-1.0,-1.0,-9.0,-21.0,-95.0,-90.0,0
4646,-35.0,-4.0,-6.0,0.0,-4.0,-11.0,-24.0,-27.0,46.0,12.0,...,-2.0,-2.0,-1.0,-3.0,2.0,5.0,36.0,51.0,6.0,0
4647,-34.0,-17.0,-4.0,10.0,14.0,-22.0,-6.0,-24.0,-17.0,26.0,...,-8.0,-23.0,-26.0,-6.0,-4.0,10.0,-13.0,-33.0,-14.0,0
4648,21.0,3.0,0.0,-15.0,5.0,2.0,48.0,22.0,-22.0,2.0,...,-7.0,-2.0,3.0,-4.0,-25.0,12.0,0.0,10.0,-33.0,0
4649,3.0,31.0,0.0,-6.0,-16.0,2.0,-38.0,-35.0,-19.0,-17.0,...,9.0,-3.0,-10.0,-9.0,14.0,-1.0,-1.0,-31.0,-18.0,0

## Q1. pose값에 따른 각 motion컬럼의 중간값의 가장 큰 차이를 보이는 motion컬럼은 어디이며 그값은?

In [3]:
temp = df.groupby('pose').median().T

In [4]:
abs(temp[0] - temp[1]).sort_values()

motion_0     0.0
motion_24    0.0
motion_25    0.0
motion_26    0.0
motion_32    0.0
            ...
motion_30    3.0
motion_38    3.0
motion_46    3.5
motion_54    4.0
motion_62    4.0
Length: 64, dtype: float64

=> motion_54, motion_62

-----------

# 8주차 예상문제 2

데이터 출처 :https://www.kaggle.com/mysarahmadbhat/hyundai-used-car-listing(참고, 데이터 수정)

데이터 설명 : 현대 차량가격 분류문제

Data url :hhttps://raw.githubusercontent.com/Datamanim/datarepo/main/hyundai/train.csv

출처 : 8주차 예상문제 2 (이기적 스터디 카페 / 컴활,정보처리,빅분기) | 작성자 빅분기 실기조교

In [5]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/hyundai/train.csv")

In [6]:
df

,model,year,price,transmission,mileage,fuelType,tax(£),mpg,engineSize
0,Tucson,2016,12795,Manual,36263,Diesel,30,61.7,1.7
1,I10,2012,3995,Manual,22089,Petrol,20,61.4,1.2
2,I30,2019,24000,Manual,555,Petrol,145,34.0,2.0
3,Tucson,2017,12995,Manual,32147,Diesel,30,61.7,1.7
4,Tucson,2018,14991,Semi-Auto,32217,Diesel,150,57.6,1.7
...,...,...,...,...,...,...,...,...,...
3883,I10,2016,6500,Manual,16309,Petrol,30,57.6,1.2
3884,Tucson,2018,15999,Semi-Auto,7723,Diesel,145,57.6,1.7
3885,I30,2016,8990,Manual,33466,Diesel,0,78.4,1.6
3886,Ioniq,2019,18990,Automatic,11816,Hybrid,135,78.5,1.6
3887,I10,2017,7998,Manual,19625,Petrol,145,57.7,1.2

## 정보(row수)가 가장 많은 상위 3차종의 price값의 각 평균값은?

In [7]:
model_list = df.groupby('model').size().sort_values().index[-3:].to_list()

In [8]:
model_list

[' I30', ' I10', ' Tucson']

In [9]:
df[df['model'].isin(model_list)].groupby('model').mean()['price']

model
 I10        7646.137891
 I30       11651.821759
 Tucson    15805.441373
Name: price, dtype: float64